### ISSUE TITLE
Email address can have multiple `@` signs

### ISSUE THREAD

**Issue by matiuszka** [JoshData/python-email-validator#103]
Email address local part can have multiple `@` signs as long as the local part is in quotes:
```python
>>> validate_email('"very.(),:;<>[]\".VERY.\"very@\\ \"very\".unusual"@strange.example.com')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/matnowak/.pyenv/versions/3.10.6/lib/python3.10/site-packages/email_validator/__init__.py", line 304, in validate_email
    raise EmailSyntaxError("The email address is not valid. It must have exactly one @-sign.")
email_validator.EmailSyntaxError: The email address is not valid. It must have exactly one @-sign.
```
ref: https://www.rfc-editor.org/rfc/rfc5322#section-3.2.4

**Comment by JoshData** [comment]
This is not supported by design. It's discussed in the README. If you need to accept addresses like that, there are some suggested alternative libraries listed right at the top of the README.

**Comment by matiuszka** [comment]
Ok, thanks for the clarification.
