### ISSUE TITLE
AttributeError: module 'dns' has no attribute 'resolver'

### ISSUE THREAD

**Issue by Olegt0rr** [JoshData/python-email-validator#139]
```python
2024-05-01 14:07:56,859 -   49: app.handlers.error_handlers.basic_errors - ERROR - ERROR! Traceback (most recent call last):

  File "/Users/t0rr/Library/Caches/pypoetry/virtualenvs/true_mafia_game-_4o18Ra--py3.11/lib/python3.11/site-packages/aiogram/dispatcher/filters/builtin.py", line 583, in check
    raise exception

  File "/Users/t0rr/Library/Caches/pypoetry/virtualenvs/true_mafia_game-_4o18Ra--py3.11/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 1397, in process_response
    response = task.result()
               ^^^^^^^^^^^^^

  File "/Users/t0rr/PycharmProjects/TrueMafia/app/handlers/misc_handlers/email_handler.py", line 30, in handle_email
    valid = validate_email(email)
            ^^^^^^^^^^^^^^^^^^^^^

  File "/Users/t0rr/Library/Caches/pypoetry/virtualenvs/true_mafia_game-_4o18Ra--py3.11/lib/python3.11/site-packages/email_validator/validate_email.py", line 140, in validate_email
    deliverability_info = validate_email_deliverability(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/t0rr/Library/Caches/pypoetry/virtualenvs/true_mafia_game-_4o18Ra--py3.11/lib/python3.11/site-packages/email_validator/deliverability.py", line 32, in validate_email_deliverability
    dns_resolver = dns.resolver.get_default_resolver()
                   ^^^^^^^^^^^^

AttributeError: module 'dns' has no attribute 'resolver'
NoneType: None
```

**Comment by JoshData** [comment]
I think something must be wrong with your environment or another package is conflicting with the dnspython package required by email-validator.

**Comment by sai8151** [comment]
- Try updating packages
- if didn't resolve reinstall everything
