### ISSUE TITLE
Bug in ValidatedEmail method __eq__

### ISSUE THREAD

**Issue by yassam** [JoshData/python-email-validator#67]
Try the following:

```
>>> from email_validator import validate_email
>>> v = validate_email('foo@test.com')
>>> v == "hello"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/yhassan/source/deferit/deferit/.env/lib/python3.8/site-packages/email_validator/__init__.py", line 146, in __eq__
    self.email == other.email
AttributeError: 'str' object has no attribute 'email'
```

In other words, if `v` is an instance of `ValidatedEmail` and you do something like `if v == 'abc'` or `if v == None`, it throws an exception.

I created a PR which fixes this: https://github.com/JoshData/python-email-validator/pull/66

**Comment by JoshData** [comment]
Merged, thanks!
